# Generated by Django 5.2.8 on 2025-11-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_horas', models.FloatField()),
                ('fecha', models.DateField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pys.car')),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='api_pys.city')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='api_pys.city')),
            ],
        ),
    ]
